version: '3.1'

services:
  node-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: Password1234
# docker ps
# docker inspect nodejscourse_node-mysql_1 -f "{{json .NetworkSettings.Networks }}"
# docker run -it --network nodejscourse_default --rm mysql mysql -hnodejscourse_node-mysql_1 -uroot -p
